- name: bug
  description: Something isn't working
  color: d42a34

- name: dependencies
  description: Related with project dependencies
  color: ffc0cb

- name: documentation
  description: Improvements or additions to documentation
  color: 0677ba

- name: enhancement
  description: New features or code improvements
  color: FFD827

- name: good first issue
  description: Easy to solve for newcomers
  color: 62ca50

- name: maintenance
  description: Package and maintenance related
  color: f78c37

- name: release
  description: Anything related to an incoming release
  color: ffffff

- name: hacktoberfest
  description: Hacktoberfest related
  color: 62ca50

- name: hacktoberfest-accepted
  description: Hacktoberfest accepted contribution
  color: 62ca50

- name: css
  description: Requires or modifies cascading style sheets
  color: d4c5f9

- name: js
  description: Requires or modifies JavaScript code
  color: fef2c0

- name: ui/ux
  description: Related with UI/UX design
  color: ffffff
