repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.2
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: 'v4.0.0-alpha.8'
  hooks:
  - id: prettier
    types_or: [css, javascript]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.2
  hooks:
    - id: check-github-workflows

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.4.3
  hooks:
  - id: add-license-headers
    files: '(src|doc/source/examples)/.*\.(py)'
    args:
    - --start_year=2021
