repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: ["--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt", "-w"]

- repo: "https://github.com/pycontribs/mirrors-prettier"
  rev: v3.4.2
  hooks:
  - id: prettier
    types_or: [css, javascript]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

- repo: "https://github.com/Riverside-Healthcare/djLint"
  rev: v1.36.4
  hooks:
    - id: djlint-jinja
      types_or: ["html"]
      ignore: "T003"

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.31.1
  hooks:
    - id: check-github-workflows

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.5.1
  hooks:
  - id: add-license-headers
    files: '(src|doc/source/examples)/.*\.(py)'
    args:
    - --start_year=2021
