name: Build

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  precommit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install pyansys_sphinx_theme
        run: |
          python setup.py sdist
          pip install dist/pyansys*.tar.gz --disable-pip-version-check
  
      - name: lint package
        run: |
          pip install twine
          twine check dist/*

      - name: Build Documentation
        run: |
          pip install -r requirements_docs.txt
          make -C doc html SPHINXOPTS="-W"
          touch doc/build/html/.nojekyll
          echo "sphinxdocs.pyansys.com" > doc/build/html/CNAME
  
      - name: Upload Documentation
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Documentation
          path: doc/build/html
          retention-days: 7

      - name: Deploy to gh-pages
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: JamesIves/github-pages-deploy-action@3.7.1        
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/build/html
          CLEAN: true
          SINGLE-COMMIT: true

  Release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [precommit, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Generate package
        run: python setup.py sdist

      - name: Upload to Public PyPi
        run: |
          pip install twine
          twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true