name: Build

on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  stylecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Check Style
        run: |
          pip install .[style]
          make

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Verify package can be built
        run: |
          pip install -U pip build
          python -m build

      - name: Install
        run: |
          python -m pip install -e .[doc]

      - name: Build Documentation
        run: |
          make -C doc html SPHINXOPTS="-W"
          touch doc/build/html/.nojekyll
          echo "sphinxdocs.pyansys.com" > doc/build/html/CNAME
  
      - name: Upload Documentation
        uses: actions/upload-artifact@v2.2.1
        with:
          name: Documentation
          path: doc/build/html
          retention-days: 7

      - name: Deploy to gh-pages
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: JamesIves/github-pages-deploy-action@3.7.1        
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/build/html
          CLEAN: true

  Release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
    needs: [stylecheck, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Build package
        run: |
          pip install -U pip build
          python -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.TWINE_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true